Update Basic.md (Pull request still wip)
Alzymologist/Kuvio-model pull request #5
Opened 2024-03-11 20:56 UTC by Evgenii-Barannik

2024-03-14 14:15 UTC, Evgenii-Barannik commented
@Slesarew Please add all the things that shouldn't have been deleted. That is all.

2024-03-15 21:18 UTC, Slesarew requested changes

2024-03-15 21:18 UTC, Slesarew commented on docs/Basic.md
> +3. Observe whether tile behaviour difference from the reservoir or tile-membership considering decision-making has more influence.
```suggestion
3. Observe whether tile behaviour difference from the reservoir or tile-membership considering decision-making has more influence.
4. Determine required difference in behaviour to make tile more successful than reservoir with basic 2-game, 1-game, and declinable 2-game
5. Determine where 2-game and diclinable 2-game diverge
```

2024-03-15 21:18 UTC, Slesarew commented on docs/Basic.md
> +We define the growth of a resource as desired and its loss as undesired.
```suggestion
We define the growth of a resource as desired and its loss as undesired.

To evaluate desiredness, we use utility function; that is, logarithm of resource. This is mainly manifested through utility change (derivative value as 1/x), which would probably be useless in simplest model.
```

2024-03-15 21:18 UTC, Slesarew commented on docs/Basic.md
> +Behaviour is a specific action that can transform the state of a **tile**, but in the most cases it is focused on the state of the acting **agent**. In our simplest model, each behaviour is associate
Behaviour is not an action, it is a decision making algorithm. Decision is not an action but an input to action generation. In simplest models these would be bijective, but not in general case.

Behavior does not change the state more than any other entity in the system.

```suggestion
Behaviour is a decision making algorithm of an **agent**, essentially probability distribution of agent making certain decisions in generating and playing **games**. Behaviours can be simple but may also contain arbitrarily complex logic, probably even including pointers to other behaviours (tho control must flow along directed acyclic graph in the end). Inputs to decision-making may include internal agent behaviour variables and resources, as well as external parameters like reputations. Behaviour should be hidden from all parts of the system except for the agent handling mechanism, but information about it is revealed through the **games** unfolding.
```

Section on different behavior on different tiles seems quite self-evident and unnecessary now that I think about it.

2024-03-15 21:18 UTC, Slesarew commented on docs/Basic.md
> +We define a tile as a community of **agents** with a list of **reputation** values between agents (allowing us to refer to reputations as "relational resources"). A tile is finite and thus can only b
Reputation is not really a resource as it does not have to be integer, does not even have to be algebraic or have order or equality relations.

Tile could also have a treasury of actual resources for its maintenance. Tile is also defined by rule sets. I did not intend to describe these details here yet. Thus it's a general community of actors that may have arbitrary properties until we figure out what requirements are. I know of finite size that's important for efficient statistics right now, but not more.

It is important that tile could be subsampled by selection, as opposed to effectively infinite reservoir. Limiting number of agents, although good idea in general, is not a necessary requirement. We've envisioned reservoir-sized "Humanity" tile, although there is no clear understanding of its nature yet - would it be efficient to subsample it? Let's leave it to later times.

```suggestion
We define a tile as a community of **agents**, possibly with some rules, a list of **reputation** values between agents, and treasuries to store communal resources. A tile is finite and thus could be subsampled by selection of actors.
```

2024-03-15 21:18 UTC, Slesarew commented on docs/Basic.md
> +A game event is defined by the number and parameters of **agents**, their courses of actions, and outcomes. A game event changes **resource** distribution, **reputation**, and exposes information abo
```suggestion
A game event is defined by the number and parameters of **agents**, their courses of actions, and outcomes. A game event changes **resource** distribution, **reputation**, and exposes information about the chosen course of action, thus revealing information about agents' behaviours.

### Basic two-actor game

Two **actors** approach the game. Both have symmetric options to collaborate or cheat, thus 4 outcomes are possible. Resource change in a **game** is model parameter that should be adjusted to experimental conditions.

### Basic one-actor game

One **actor** participates and has options to collaborate or cheat, **resource** change is a model parameter

### Declinable two-actor game

Two actors participate. Bothe have symmetric options to collaborate, cheat, or decline. If either declines, no resource change happens. Thus 5 outcomes are possible. Otherwise it is similar to basic 2-actor game.
```

2024-03-16 00:31 UTC, Evgenii-Barannik commented
All is ok except this, I am not sure if this is still correct, so i will remove this in text:

> The order in which agents execute their behaviours on each game tick is defined to be the same as the order in which agents were created. (line 31)

The discussion about this was already started in another pull-request so you can just approve here.

2024-03-17 19:23 UTC, Slesarew approved these changes

2024-03-17 19:23 UTC, merged